name: ServerEconSim
main: me.becja10.ServerEconSim.ServerEconSim
author: 10becja
version: 1.3
description: An economy plugin that simulates the server requesting items from players
depend: [Vault]
softdepend: [Multiverse-Core]
commands:
  reloadrequests:
    description: reloads the plugin and all configs
    usage: /<command>
  setrequest:
    description: Allows for setting requests ingame. Hold the item (and amount) that you wish to make a request of.
    usage: /<command> <amount> <base price> <1-5> (optional custom display name)
  viewrequests:
    description: Shows what requests are available and which you've already completed
    usage: /<command>
  listrequests:
    description: Lists all requests according to the criteria
    usage: /<command> <filter> <page>
  requestdetails:
    description: Gets all details for a request id
    usage: /<command> <id>
  editrequest:
    description: Allows for editing a request id. Works similar to setrequest, but overwrites the provided id
    usage: /<command> <id> <amount> <base price> <1-5> (optional custom desiplay name)